services:
  - type: web
    name: group-meg-bot-new
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: group-meg-bot-new
          property: url
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        value: sqlite:///bot.db
